### ISSUE TITLE
setup env for react/client-side

### ISSUE THREAD

**Issue by levensspel** [Kucing-Garasi/kuberkeluh#13]

**Comment by sriabhinay556** [comment]
do you want to move the entire codebase to NextJS?

**Comment by TrigrD3** [comment]
Sure if you can help with that @sriabhinay556 that would be awesome

**Comment by sriabhinay556** [comment]
alright, I am creating a brand new project with next14 and implement the existing code, is that alright?

**Comment by TrigrD3** [comment]
Sounds good, make sure you pull from feature-react branch

**Comment by levensspel** [comment]
For the tech migration related issue can be opened as a new issue.
